name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          pnpm-version: 8.5.1
      - name: Install dependencies
        run: pnpm install
      - name: Build addon
        run: pnpm build
      - name: auto-dist-tag
        run: npx auto-dist-tag@1 --write
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ember-amount-input
